version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=sqlite:///./blog.db
      - REDIS_URL=${REDIS_URL}
redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}

